GET http://localhost:8080/games

###

GET  http://localhost:8080/games/as

###
POST http://localhost:8080/games
Content-Type: application/json

{
    "players": [
        {
            "name": "Pablo"
        },
        {
            "name": "Franco"
        },
        {
            "name": "Valeska"
        },
        {
            "name": "Magaly"
        },
        {
            "name": "Luis"
        }
    ]
}

### 
PATCH  http://localhost:8080/games/64f6368301be4f42da356494
Content-Type: application/json

{
    "players": [
        {
            "name": "Hugo",
            "points": 100
        },
        {
            "name": "Andres",
            "points": 0
        }
    ]
}

###
DELETE http://localhost:8080/games/sad
Content-Type: application/json