GET http://localhost:8080/games

###

GET  http://localhost:8080/games/651b0fdc98e3a1b9dce4897e

###
POST http://localhost:8080/games
Content-Type: application/json

{
    "players": [
        {
            "name": "Pablo"
        },
        {
            "name": "Franco"
        },
        {
            "name": "Valeska"
        },
        {
            "name": "Magaly"
        },
        {
            "name": "Luis"
        }
    ]
}

### 
PATCH  http://localhost:8080/games/64f6368301be4f42da356494
Content-Type: application/json

{
    "players": [
        {
            "name": "Hugo",
            "points": 100
        },
        {
            "name": "Andres",
            "points": 0
        }
    ]
}

###
DELETE http://localhost:8080/games/651dddecbee34f90e6988fc3
Content-Type: application/json