GET http://localhost:8080/games

###

GET  http://localhost:8080/games/64f63996333a6960665f0efc

###
POST http://localhost:8080/games
Content-Type: application/json

{
    "players": [
        {
            "name": "Pablo"
        },
        {
            "name": "Franco"
        },
        {
            "name": "Valeska"
        },
        {
            "name": "Magaly"
        },
        {
            "name": "Luis"
        }
    ]
}

### 
PATCH  http://localhost:8080/games/64f6368301be4f42da356494
Content-Type: application/json

{
    "players": [
        {
            "name": "Talia",
            "points": 300
        },
        {
            "name": "Barbara"
        }
    ]
}

###
DELETE http://localhost:8080/games/64f63be8fa9ad7400a7e7ac7
Content-Type: application/json